#name of workflow
name: Deploy AWS Lambda 

#defines when workflow is intialized 
on: 
    push:   #any time there is a push, it will trigger the workflow below
        branches:
            - main
        paths:
            - 'lambda/**'
            
#defines all jobs that need to run inside workflow
jobs:
    deploy-lambda:  #name of your job 
        runs-on: ubuntu-latest #sets or specifies the runner
        steps:
        - uses: actions/checkout@v2

        - name: Set Up Python   #sets up python enviorment 
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install Dependencies #installs any packages
          run: |
                python -m pip install --upgrade pip
                pip install -r lambda/requirements.txt -t lambda/
       
        - name: Configure AWS Creds #sets up your AWS credentials 
          uses: aws-actions/configure-aws-credentials@v1 
          with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        
        - name: Deploy Lambda Function #Zips lambda directory and updates lambda function 
          run: |
            cd lambda 
            zip -r lambda.zip .
            aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
